# Generated by Django 5.0.4 on 2024-05-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='id',
            new_name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
